# Generated by Django 5.2.12 on 2026-04-23 05:34

import inspect
import django.db.models.deletion
import uuid
from django.db import migrations, models

_CHECK_KW = (
    "condition"
    if "condition" in inspect.signature(models.CheckConstraint.__init__).parameters
    else "check"
)


def _variant_stock_non_negative_constraint():
    """Django 5.0 va eski versiyalar `check=`; ba'zi yangi versiyalar `condition=` ishlatadi."""
    q = models.Q(stock_qty__gte=0)
    if _CHECK_KW == "condition":
        return models.CheckConstraint(condition=q, name="variant_stock_non_negative")
    return models.CheckConstraint(check=q, name="variant_stock_non_negative")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
                ('label_uz', models.CharField(max_length=64)),
                ('label_ru', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=32)),
                ('label_uz', models.CharField(max_length=64)),
                ('label_ru', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'is_active'], name='catalog_pro_product_6c5ee9_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('product', 'size', 'color'), name='uniq_product_size_color'),
                    _variant_stock_non_negative_constraint(),
                ],
            },
        ),
    ]
