# Generated by Django 5.2.9 on 2026-05-20 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_size_color_appliance_customization'),
        ('sales', '0006_phase4_serial_warranty_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.CharField(blank=True, help_text='e.g., 330L, 7kg', max_length=100)),
                ('power_consumption', models.CharField(blank=True, help_text='e.g., 150W, 2.5kW', max_length=100)),
                ('voltage', models.CharField(blank=True, help_text='e.g., 220V, 110-240V', max_length=50)),
                ('dimensions', models.CharField(blank=True, help_text='e.g., 60x65x185cm', max_length=100)),
                ('weight', models.CharField(blank=True, help_text='e.g., 65kg', max_length=50)),
                ('color_options', models.CharField(blank=True, help_text='e.g., White, Silver, Black', max_length=200)),
                ('energy_class', models.CharField(blank=True, help_text='e.g., A++, A+, B', max_length=20)),
                ('additional_specs', models.JSONField(blank=True, default=dict, help_text='Additional specifications as key-value pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('DEFECTIVE', 'Defective')], default='IN_STOCK', max_length=16)),
                ('warranty_months', models.PositiveIntegerField(default=12, help_text='Warranty period in months')),
                ('purchase_date', models.DateField(blank=True, help_text='Date purchased from supplier', null=True)),
                ('sale_date', models.DateField(blank=True, help_text='Date sold to customer', null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, help_text='Calculated warranty expiry date', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_serial_numbers', to=settings.AUTH_USER_MODEL)),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='sales.saleline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'status'], name='catalog_ser_variant_8062c8_idx'), models.Index(fields=['status', '-created_at'], name='catalog_ser_status_44426b_idx'), models.Index(fields=['warranty_expiry_date'], name='catalog_ser_warrant_2b2d03_idx'), models.Index(fields=['sale_date'], name='catalog_ser_sale_da_7b4d39_idx')],
            },
        ),
    ]
