# Generated by Django 5.2.9 on 2026-05-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_phase4_serial_warranty_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name_uz_cyrillic',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='note',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
