# Generated by Django 5.2.12 on 2026-04-23 05:34

import inspect
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

_CHECK_KW = (
    "condition"
    if "condition" in inspect.signature(models.CheckConstraint.__init__).parameters
    else "check"
)


def _saleline_qty_positive_constraint():
    """Django 5.0 va eski versiyalar `check=`; ba'zi yangi versiyalar `condition=` ishlatadi."""
    q = models.Q(qty__gt=0)
    if _CHECK_KW == "condition":
        return models.CheckConstraint(condition=q, name="saleline_qty_positive")
    return models.CheckConstraint(check=q, name="saleline_qty_positive")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], default='COMPLETED', max_length=16)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('export_last_error', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('DEBT', 'Debt')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('list_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.productvariant')),
            ],
            options={
                'constraints': [_saleline_qty_positive_constraint()],
            },
        ),
    ]
