# Generated by Django 5.2.9 on 2026-05-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salerefund'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salerefund',
            new_name='sales_saler_created_95ff54_idx',
            old_name='sales_saler_created_6e8f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='salerefund',
            new_name='sales_saler_sale_id_519287_idx',
            old_name='sales_saler_sale_id_8c4b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='salerefund',
            new_name='sales_saler_method_8d56eb_idx',
            old_name='sales_saler_method_91a3bc_idx',
        ),
    ]
