# Generated by Django 5.2.9 on 2026-05-20 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='shopexpense',
            name='related_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.shift'),
        ),
        migrations.AddIndex(
            model_name='shopexpense',
            index=models.Index(fields=['recorded_at'], name='expenses_sh_recorde_1aadbc_idx'),
        ),
        migrations.AddIndex(
            model_name='shopexpense',
            index=models.Index(fields=['related_shift', '-recorded_at'], name='expenses_sh_related_ce4b24_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['cashier', 'status'], name='expenses_sh_cashier_c81e42_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['-opened_at'], name='expenses_sh_opened__9d041f_idx'),
        ),
    ]
